beelab_paypal:
    username: "grmcteam_api1.gmail.com"
    password: "L6XVMH3PDDAPNF4H"
    signature: "AnvV9leb2hxXC1GpSXnr1tGl1hINA1U2RqGixjKkrShYLpaX.8qFoMrw"
    return_route: "success_payment"
    cancel_route: "error_payment"
    test_mode: true
