security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        artisan:
            pattern: ^/artisan
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_artisan_login
                check_path: fos_user_security_artisan_check
                always_use_default_target_path: true
                default_target_path: /artisan/dashbord

            logout:
                path: fos_user_security_artisan_logout

            anonymous:    true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /artisan

        admin:
            pattern: ^/admin
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_admin_login
                check_path: fos_user_security_admin_check
                always_use_default_target_path: true
                default_target_path: /admin/dashboard

            logout:
                path: fos_user_security_admin_logout

            anonymous:    true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /admin

        client:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /client


            logout:       true
            anonymous:    true



    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/artisan/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/artisan/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/artisan/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/artisan$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/client/specialite/, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/artisan/, role: ROLE_ARTISAN }
    - { path: ^/client, role: ROLE_CLIENT }
    - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, role: ROLE_ADMIN }
